app/blueprints/posts/forms.py
from wtforms import Form, StringField, PasswordField, BooleanField, SubmitField, SelectField, RadioField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, InputRequired
from wtforms import TextAreaField, SelectMultipleField

from flask_wtf import FlaskForm

from app import app, tag_choices
from app.models import *

# try:
#     tag_choices = [(tag.name, tag.slug)  for tag in Tag.query.all()]
# except:
#     tag_choices = []

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Say something', validators=[DataRequired()])
    tags = RadioField(
        'Select tags', choices=tag_choices, validators=[DataRequired()])
    submit = SubmitField('Submit')

blueprints/posts/forms.py
from wtforms import Form, StringField, PasswordField, BooleanField, SubmitField, SelectField, RadioField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, InputRequired
from wtforms import TextAreaField

from flask_wtf import FlaskForm

from app import app
from models import *


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Say something', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/blueprints/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import flash, redirect
from flask import redirect
from flask import url_for
from flask import request

from flask_login import login_user
from flask_login import logout_user
from flask_login import current_user
from flask_login import login_required

from .forms import PostForm

from app import app
from app import db
from app import log
from app.models import *

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()
    form = PostForm(formdata=request.form, obj=post)
    print('edited', form.validate_on_submit())
    if form.validate_on_submit():
        # form.populate_obj(post)
        post.title = form.title.data
        post.body = form.body.data
        try:
            post.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            db.session.commit()
            flash('Your post edited')
            log.info("User '%s' edit post '%s'." % (current_user.username, post.title))
            return redirect(url_for('posts.post_detail', slug=post.slug))
        except:
           redirect('posts.index') 
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', form=form)

@posts.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data, 
            body=form.body.data, 
            author=current_user, 
            )
        try:
            post.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            db.session.add(post)
            db.session.commit()
            flash('Your post is now live!')
            return redirect(url_for('posts.index'))
        except:
            redirect('posts.index') 

    q = request.args.get('q')
    page = request.args.get('page')
    page = request.args.get('page', 1, type=int)
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q).all())
    else:
        posts = Post.query.order_by(Post.created.desc())
        
    pages = posts.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])
    # max pages = posts.count() or 404
    return render_template('posts/index.html', form=form, pages=pages)

@posts.route('/<slug>')
@login_required
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags, user=current_user)

@posts.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts_tags.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

blueprints/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import flash, redirect
from flask import redirect
from flask import url_for
from flask import request

from flask_login import login_user
from flask_login import logout_user
from flask_login import current_user
from flask_login import login_required

from .forms import PostForm

from app import app
from app import db
from models import *

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()
    form = PostForm(formdata=request.form, obj=post)

    if form.validate_on_submit():
        # form.populate_obj(post)
        post.title = form.title.data
        post.body = form.body.data
        try:
            post.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            db.session.commit()
            flash('Your post edited')
            return redirect(url_for('posts.post_detail', slug=post.slug))
        except:
           redirect('posts.index') 
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', form=form)

@posts.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data, 
            body=form.body.data, 
            author=current_user, 
            )
        try:
            post.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            db.session.add(post)
            db.session.commit()
            flash('Your post is now live!')
            return redirect(url_for('posts.index'))
        except:
            redirect('posts.index') 

    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page) 
    else:
        page = 1 
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q).all())
    else:
        posts = Post.query.order_by(Post.created.desc())
        
    pages = posts.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])
    # max pages = posts.count() or 404
    return render_template('posts/index.html', form=form, pages=pages)

@posts.route('/<slug>')
@login_required
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags, user=current_user)

@posts.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts_tags.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/blueprints/posts/templates/posts/edit_post.html
{% extends 'base.html' %} {% block title %} Edit post {% endblock %} {% block content_title %}
<h3>Edit post: {{form.title.data}}</h3>
{% endblock %} {% block content %} {% if form %}
<div>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label(class='control-label') }}<br> {{ form.title(class='form-control') }}<br> {% for error in form.title.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
            <br> {{ form.body.label(class='control-label') }}<br> {{ form.body(class='form-control') }}<br> {% for error in form.body.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %} {{ form.tags.label(class='control-label') }}<br> {{ form.tags() }}<br> {% for error in form.tags.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
        </div>
        {{ form.submit(class="btn btn-success") }}
    </form>

</div>
{% endif %} {% endblock %}

app/blueprints/posts/templates/posts/index.html
{% extends 'base.html' %} {% block title %} Blueprint post title {% endblock %} {% block content_title %}
<h3>Posts</h3>
{% endblock %} {% block content %} {% for post in pages.items %}
<div class="main-content">
    <table>
        <tr>
            <td><img src="{{ url_for('static', filename=post.author.avatar()) }}" width="30" height="30" alt="avatar"></td>
            <td><a href="{{ url_for('user', username=post.author.username) }}">
                {{ post.author.username }}</a> {{ post.created }} says :
                <br>
                <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
                <br> {{ post.body }}
                <div class="tags">
                    tags: {% for tag in post.tags %}
                    <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                        <span class="label label-primary">{{ tag.name }}</span></a> {% endfor %}
                </div>
            </td>
        </tr>
    </table>
</div>
<br> {% endfor %}
<nav>
    <ul class="pagination">
        <li {% if not pages.has_prev %} class="disabled" {% endif %}>
            <a href="./?page={{ pages.prev_num }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span></a>
        </li>
        {% for page in pages.iter_pages() %}
        <li {% if page==pages.page %} class="active" {% endif %}><a href="./?page={{ page }}">{{page}} <span class="sr-only">(current)</span></a></li>
        {% endfor %}
        <li {% if not pages.has_next %} class="disabled" {% endif %}>
            <a href="./?page={{ pages.next_num }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span></a>
        </li>
    </ul>
</nav>
<hr> Create post
<div>
    {% if form %}
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label(class='control-label') }}<br> {{ form.title(class='form-control') }}<br> {% for error in form.title.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
            <br> {{ form.body.label(class='control-label') }}<br> {{ form.body(class='form-control') }}<br> {% for error in form.body.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %} {{ form.tags.label(class='control-label') }}<br> {{ form.tags() }}<br> {% for error in form.tags.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
    {% endif %}
</div>
{% endblock %}

app/blueprints/posts/templates/posts/post_detail.html
{% extends 'base.html' %} {% block title %} {{ post.title }} {% endblock %} {% block content_title %} {{ post.title }} {% endblock %} {% block content %}

<div class="main-content">
    {{ post.body }}
</div>
<div class="tags">
    {% for tag in tags %}
    <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
        <span class="label label-primary">{{ tag.name }}</span></a> {% endfor %}
</div>
<hr> {% if post.user_id==current_user.id %}
<a href="{{ url_for('posts.edit_post', slug=post.slug)}}">
    Edit post</a> {% endif %} {% endblock %}

app/blueprints/posts/templates/posts/tag_detail.html
{% extends 'base.html' %} {% block title %} {{ tag.name }} posts {% endblock %} {% block content_title %} Posts for "{{ tag.name }}" tag: {% endblock %} {% block content %} {% for post in posts %}
<div class="post">
    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
</div>
{% endfor %}

<div class="main-content">
</div>
{% endblock %}