app/blueprints/users/forms.py
from wtforms import Form, StringField, PasswordField, BooleanField, SubmitField, SelectField, RadioField, SelectMultipleField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, InputRequired
from wtforms import TextAreaField

from flask_wtf import FlaskForm


from app import app, tag_choices
from app.models import *

cities = app.config['CITIES']


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])  
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    city = RadioField('Select your city', validators=[DataRequired()],
                    choices=[(city['label'], city['value']) for city in cities])
    tags = RadioField('Select your hobby', validators=[DataRequired()],
                    choices=tag_choices)               
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

blueprints/users/forms.py
from wtforms import Form, StringField, PasswordField, BooleanField, SubmitField, SelectField, RadioField, SelectMultipleField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, InputRequired
from wtforms import TextAreaField

from flask_wtf import FlaskForm

from app import app
from models import *

cities = app.config['CITIES']
tag_choices = [(tag.name, tag.slug)  for tag in Tag.query.all()]

class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])  
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    city = RadioField('Select your city', validators=[DataRequired()],
                    choices=[(city['label'], city['value']) for city in cities])
    tags = RadioField('Select your hobby', validators=[DataRequired()],
                    choices=tag_choices)               
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

app/blueprints/users/blueprint.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, send_from_directory
from flask_login import login_user, logout_user, current_user, login_required
from .forms import EditProfileForm

from app import app, log
from app import db
from app.models import *

users = Blueprint('users', __name__, template_folder='templates')


@app.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.created.desc())
    pages = posts.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])

    events = user.events.order_by(Event.created.desc())
    event_pages = events.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])

    return render_template('users/index.html', user=user, pages=pages, event_pages=event_pages)

@users.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    users = tag.users_tags.all()
    return render_template('users/tag_detail.html', tag=tag, users=users)


@users.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        current_user.city = form.city.data
        current_user.tags.append(Tag.query.filter_by(name=form.tags.data).first())
        db.session.commit()
        flash('Your changes have been saved.')
        log.info("User '%s' edit profile." % (current_user.username))
        return redirect(url_for('user', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('users/edit_profile.html', title='Edit Profile', form=form)


@users.route('/follow/<username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('users.index'))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('users.index', username=username))
    current_user.follow(user)
    db.session.commit()
    flash('You are following {}!'.format(username))
    log.info("User '%s' following user '%s'." % (current_user.username, username))
    return redirect(url_for('posts.index', username=username))


@users.route('/unfollow/<username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('users.index'))
    if user == current_user:
        flash('You cannot unfollow yourself!')
        return redirect(url_for('users.index', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following {}.'.format(username))
    log.info("User '%s' unfollowing user '%s'." % (current_user.username, username))
    return redirect(url_for('posts.index', username=username))

blueprints/events/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import flash, redirect
from flask import redirect
from flask import url_for
from flask import request

from flask_login import login_user
from flask_login import logout_user
from flask_login import current_user
from flask_login import login_required

from .forms import EventForm

from app import app
from app import db
from models import *

events = Blueprint('events', __name__, template_folder='templates')

@events.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit_event(slug):
    event = Event.query.filter(Event.slug==slug).first()
    form = EventForm(formdata=request.form, obj=event)

    if form.validate_on_submit():
        event_title=form.event_title.data, 
        event_body=form.event_body.data, 
        event_time= form.event_time.data,
        event_place = form.event_place.data,
        event_geo = form.event_geo.data,
        try:
            event.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            db.session.commit()
            flash('Your event edited')
            return redirect(url_for('events.post_detail', slug=event.slug))
        except:
           redirect('events.index') 
    form = EventForm(obj=event)
    return render_template('events/edit_event.html', form=form)

@events.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = EventForm()
    if form.validate_on_submit():
        event = Event(
            event_title=form.event_title.data, 
            event_body=form.event_body.data, 
            event_time= form.event_time.data,
            event_place = form.event_place.data,
            event_geo = form.event_geo.data,
            event_author=current_user)
        #try:
        event.tags.append(Tag.query.filter_by(name=form.tags.data).first())
        db.session.commit()
        flash('Your cane make event!')
        return redirect(url_for('events.index'))
        #except:
        #    redirect('index') # create!!!

    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page) 
    else:
        page = 1 
    if q:
        events = Event.query.filter(Event.event_title.contains(q) | Event.event_body.contains(q).all())
    else:
        events = Event.query.order_by(Event.created.desc())
        
    pages = events.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])

    return render_template('events/index.html', form=form, pages=pages)


@events.route('/<slug>')
@login_required
def event_detail(slug):
    event = Event.query.filter(Event.slug==slug).first()
    tags = event.tags
    return render_template('events/event_detail.html', event=event, tags=tags)

@events.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    events = tag.events_tags.all()
    return render_template('events/tag_detail.html', tag=tag, events=events)

blueprints/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import flash, redirect
from flask import redirect
from flask import url_for
from flask import request

from flask_login import login_user
from flask_login import logout_user
from flask_login import current_user
from flask_login import login_required

from .forms import PostForm

from app import app
from app import db
from models import *

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()
    form = PostForm(formdata=request.form, obj=post)

    if form.validate_on_submit():
        # form.populate_obj(post)
        post.title = form.title.data
        post.body = form.body.data
        try:
            post.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            db.session.commit()
            flash('Your post edited')
            return redirect(url_for('posts.post_detail', slug=post.slug))
        except:
           redirect('posts.index') 
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', form=form)

@posts.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data, 
            body=form.body.data, 
            author=current_user, 
            )
        try:
            post.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            db.session.add(post)
            db.session.commit()
            flash('Your post is now live!')
            return redirect(url_for('posts.index'))
        except:
            redirect('posts.index') 

    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page) 
    else:
        page = 1 
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q).all())
    else:
        posts = Post.query.order_by(Post.created.desc())
        
    pages = posts.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])
    # max pages = posts.count() or 404
    return render_template('posts/index.html', form=form, pages=pages)

@posts.route('/<slug>')
@login_required
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags, user=current_user)

@posts.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts_tags.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

blueprints/users/blueprint.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, logout_user, current_user, login_required
from .forms import EditProfileForm

from app import app
from models import *

users = Blueprint('users', __name__, template_folder='templates')

# @users.route('/')
# @login_required
# def index():
#     user = User.query.filter_by(username=current_user.username).first_or_404()
#     return render_template('users/index.html', user=user)

@app.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.created.desc())
    pages = posts.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])

    events = user.events.order_by(Event.created.desc())
    event_pages = events.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])

    return render_template('users/index.html', user=user, pages=pages, event_pages=event_pages)

@users.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    users = tag.users_tags.all()
    return render_template('users/tag_detail.html', tag=tag, users=users)


@users.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        current_user.city = form.city.data
        current_user.tags.append(Tag.query.filter_by(name=form.tags.data).first())
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('user', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('users/edit_profile.html', title='Edit Profile', form=form)


@users.route('/follow/<username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('users.index'))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('users.index', username=username))
    current_user.follow(user)
    db.session.commit()
    flash('You are following {}!'.format(username))
    return redirect(url_for('posts.index', username=username))


@users.route('/unfollow/<username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('users.index'))
    if user == current_user:
        flash('You cannot unfollow yourself!')
        return redirect(url_for('users.index', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following {}.'.format(username))
    return redirect(url_for('posts.index', username=username))

app/blueprints/users/templates/users/edit_profile.html
{% extends "base.html" %} {% block content %}
<h1>Edit Profile</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.username.label(class='control-label') }}<br> {{ form.username(class='form-control')}}<br> {% for error in form.username.errors %}
        <span style="color: red;">[{{ error }}]</span> {% endfor %}<br> {{ form.about_me.label(class='control-label') }}<br> {{ form.about_me(class='form-control') }}<br> {% for error in form.about_me.errors %}
        <span style="color: red;">[{{ error }}]</span> {% endfor %}<br> {{ form.city.label(class='control-label') }}<br> {{ form.city() }}<br> {% for error in form.city.errors %}
        <span style="color: red;">[{{ error }}]</span> {% endfor %}<br> {{ form.tags.label(class='control-label') }}<br> {{ form.tags() }}<br> {% for error in form.tags.errors %}
        <span style="color: red;">[{{ error }}]</span> {% endfor %}
        <br> {{ form.submit(class="btn btn-success") }}
</form>
{% endblock %}

app/blueprints/users/templates/users/index.html
{% extends 'base.html' %} {% block title %} User title {% endblock %} {% block content_title %} {% endblock %} {% block content %}
<table>
    <tr>
        <td><img src="{{ url_for('static', filename=user.avatar()) }}" width="60" height="60" alt="avatar" />
        </td>
        <td>
            User: {{ user.username }} <br> City: {{ user.city }}
        </td>
    </tr>
</table>
{% if user.about_me %} About me: {{ user.about_me }} {% endif %}
<br> {% for tag in user.tags %}
<a href="{{ url_for('users.tag_detail', slug=tag.slug) }}">
    <span class="label label-primary">
        {{ tag.name }}
    </span>
</a> {% endfor %}
<p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>

<hr> {% if user.last_seen %} Last seen on: {{ user.last_seen }} {% endif %} {% if user.username == current_user.username %}
<p><a href="{{ url_for('users.edit_profile') }}">Edit your profile</a></p>
{% elif not current_user.is_following(user) %}
<p><a href="{{ url_for('users.follow', username=user.username) }}">Be friend</a></p>
{% else %}
<p><a href="{{ url_for('users.unfollow', username=user.username) }}">Unfriend</a></p>
{% endif %}

<hr>
<h3>{{user.username}} posts:</h3>
{% for post in pages.items %}
<div class="main-content">
    <table>
        <tr>
            <td><img src="{{ url_for('static', filename=post.author.avatar()) }}" width="30" height="30" alt="avatar" /></td>
            <td><a href="{{ url_for('user', username=post.author.username) }}">
                {{ post.author.username }}</a> {{ post.created }} says :
                <br>
                <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
                <br> {{ post.body }}
                <div class="tags">
                    tags: {% for tag in post.tags %}
                    <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                        <span class="label label-primary">{{ tag.name }}</span></a> {% endfor %}
                </div>
            </td>
        </tr>
    </table>
</div>
<br> {% endfor %}
<nav>
    <ul class="pagination">
        <li {% if not pages.has_prev %} class="disabled" {% endif %}>
            <a href="./{{user.username}}?page={{ pages.prev_num }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span></a>
        </li>
        {% for page in pages.iter_pages() %}
        <li {% if page==pages.page %} class="active" {% endif %}>
            <a href="./{{user.username}}?page={{ page }}">{{page}} <span class="sr-only">(current)</span></a></li>
        {% endfor %}
        <li {% if not pages.has_next %} class="disabled" {% endif %}>
            <a href="./{{user.username}}?page={{ pages.next_num }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span></a>
        </li>
    </ul>
</nav>

<hr>
<h3>{{user.username}} events:</h3>
{% for event in event_pages.items %}
<div class="main-content">
    <table>
        <tr>
            <td><img src="{{ event.event_author.avatar() }}"></td>
            <td><a href="{{ url_for('user', username=event.event_author.username) }}">
                {{ event.event_author.username }}</a> {{ event.created }} says :
                <br>
                <a href="{{ url_for('events.event_detail', slug=event.slug) }}">{{ event.event_title }}</a>
                <br> {{ event.event_body }}
                <div class="tags">
                    tags: {% for tag in event.tags %}
                    <a href="{{ url_for('events.tag_detail', slug=tag.slug) }}">
                        <span class="label label-primary">{{ tag.name }}</span></a> {% endfor %}
                </div>
            </td>
        </tr>
    </table>
</div>
<br> {% endfor %}
<nav>
    <ul class="pagination">
        <li {% if not pages.has_prev %} class="disabled" {% endif %}>
            <a href="./{{user.username}}?page={{ pages.prev_num }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span></a>
        </li>
        {% for page in event_pages.iter_pages() %}
        <li {% if page==event_pages.page %} class="active" {% endif %}>
            <a href="./{{user.username}}?page={{ page }}">{{page}} <span class="sr-only">(current)</span></a></li>
        {% endfor %}
        <li {% if not pages.has_next %} class="disabled" {% endif %}>
            <a href="./{{user.username}}?page={{ pages.next_num }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span></a>
        </li>
    </ul>
</nav>
{% endblock %}

app/blueprints/users/templates/users/tag_detail.html
{% extends 'base.html' %} {% block title %} {{ tag.name }} users {% endblock %} {% block content_title %} Users for "{{ tag.name }}" tag: {% endblock %} {% block content %} {% for user in users %}
<div class="user">
    <a href="{{ url_for('user', username=user.username) }}">{{ user.username }}</a>
</div>
{% endfor %}

<div class="main-content">
</div>
{% endblock %}