app/blueprints/photos/forms.py
from wtforms import Form, StringField, PasswordField, BooleanField, SubmitField, SelectField, RadioField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, InputRequired
from wtforms import TextAreaField, SelectMultipleField

from flask_wtf import FlaskForm

from app import app, tag_choices
from app.models import *

    
class PhotoForm(FlaskForm):
    photo_title = StringField('Photo title', validators=[DataRequired()])
    photo_description = TextAreaField('Photo about', validators=[DataRequired()])
    tags = RadioField(
        'Select tags', choices=tag_choices, validators=[DataRequired()])
    submit = SubmitField('Submit')

blueprints/photos/forms.py
from wtforms import Form, StringField, PasswordField, BooleanField, SubmitField, SelectField, RadioField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, InputRequired
from wtforms import TextAreaField, SelectMultipleField

from flask_wtf import FlaskForm

from app import app
from models import *


class PhotoForm(FlaskForm):
    pass

app/blueprints/photos/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import flash, redirect
from flask import redirect
from flask import url_for
from flask import request

from flask_login import login_user
from flask_login import logout_user
from flask_login import current_user
from flask_login import login_required
from werkzeug.utils import secure_filename

from .forms import PhotoForm

from app import app
from app import db
from app import log
from app.models import *

import os

photos = Blueprint('photos', __name__, template_folder='templates')

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']

@photos.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit_info(slug):
    photo = Photo.query.filter(Photo.id==slug).first()
    form = PhotoForm(formdata=request.form, obj=photo)

    if form.validate_on_submit():
        photo.photo_title = form.photo_title.data
        photo.photo_description = form.photo_description.data
        try:
            photo.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            log.debug("Photo before db '%s'." % (photo))
            db.session.commit()
            flash('Your photo edited')

            photo = Photo.query.filter(Photo.id==slug).first()
            log.debug("Photo after db '%s'." % (photo))
            tags = photo.tags
            log.info("User '%s' edit photo info '%s'." % (current_user.username, photo.photo_title))
            return render_template('photos/photo_detail.html', photo=photo, tags=tags, user=current_user)
        except:
            redirect('photos.index') 
    form = PhotoForm(obj=photo)
    return render_template('photos/edit_info.html', form=form)           

@photos.route('/', methods=['GET', 'POST'])
@login_required
def index():
    args = {'method': 'GET'}
    # MAX_FILE_SIZE = 1024 * 1024 + 1

    user = User.query.filter(User.username == current_user.username).first()     
    user_dir = user.username + user.timestamp
    user_folders = os.path.join('user_data', user_dir, 'photos')
    photos = Photo.query.filter(Photo.photo_author==current_user).all()


    if request.method == 'POST':       
        for file in request.files.getlist('file'):
            filename =  secure_filename(file.filename)
            # if bool(file.filename):
            #     file_bytes = file.read(MAX_FILE_SIZE)
            #     args['file_size_error'] = len(file_bytes) == MAX_FILE_SIZE
            # args['method'] = 'POST'
            #destination = '/'.join([user_folders, filename])
            destination = os.path.join('app', 'static', user_folders, filename)
            if allowed_file(filename):
                file.save(destination)

                photo = Photo(
                photo_title=filename, 
                photo_description='', 
                slug='user_data/{}/{}/{}'.format(user_dir, 'photos', filename),
                photo_author=current_user, 
                )
                db.session.add(photo)
                db.session.commit()
            else:
                flash('Not allowed file extensions')
            return redirect(url_for('photos.index'))
        return redirect(url_for('photos.index'))
    return render_template('photos/index.html', args=args, photos=photos)
    

@photos.route('/<slug>')
@login_required
def photo_detail(slug):
    photo = Photo.query.filter(Photo.id==slug).first()
    tags = photo.tags
    return render_template('photos/photo_detail.html', photo=photo, tags=tags, user=current_user)

@photos.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    photos = tag.photos_tags.all()
    return render_template('photos/tag_detail.html', tag=tag, photos=photos)

blueprints/photos/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import flash, redirect
from flask import redirect
from flask import url_for
from flask import request

from flask_login import login_user
from flask_login import logout_user
from flask_login import current_user
from flask_login import login_required

from .forms import PhotoForm

from app import app
from app import db
from models import *

photos = Blueprint('photos', __name__, template_folder='templates')

@photos.route('/', methods=['GET', 'POST'])
@login_required
def index():
    return render_template('photos/index.html')

app/blueprints/photos/templates/photos/edit_info.html
{% extends 'base.html' %} {% block title %} Edit photo {% endblock %} {% block content_title %}
<h3>Edit photo info:</h3>
{% endblock %} {% block content %} {% if form %}
<div>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <br>{{ form.photo_title.label(class='control-label') }}
            <br> {{ form.photo_title(class='form-control') }}
            <br> {% for error in form.photo_title.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br> {{ form.photo_description.label(class='control-label') }}
            <br> {{ form.photo_description(class='form-control') }}
            <br> {% for error in form.photo_description.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br>{{ form.tags.label(class='control-label') }}
            <br> {{ form.tags() }}
            <br> {% for error in form.tags.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
        </div>
        {{ form.submit(class="btn btn-success") }}
    </form>
</div>
{% endif %} {% endblock %}

app/blueprints/photos/templates/photos/index.html
{% extends 'base.html' %} {% block title %} Photos title {% endblock %} {% block content_title %}
<h3>Photos</h3>
{% endblock %} {% block content %}
<div class="main-content">
    {{ current_user.username }} photos:<br> {% for photo in photos %}
    <a href="{{ url_for('photos.photo_detail', slug=photo.id) }}">
        <img src="{{ url_for('static', filename=photo.slug) }}" width="240" height="240" alt="photo" />
    </a><br> {{photo.photo_title}}
    <div class="tags">
        tags: {% for tag in photo.tags %}
        <a href="{{ url_for('photos.tag_detail', slug=tag.slug) }}">
            <span class="label label-primary">{{ tag.name }}</span></a> {% endfor %}
    </div>
    <hr> {% endfor %}
    <hr>
    <br> Photo uploader
    <form id="uload-form" action="{{ url_for('photos.index') }}" method="POST" enctype="multipart/form-data">
        <input type="file" name="file" accept="image/*" multiple>
        <input type="submit" value="Send">
    </form>

</div>
{% endblock %}

app/blueprints/photos/templates/photos/photo_detail.html
{% extends 'base.html' %} {% block title %} Photos title {% endblock %} {% block content_title %}
<h3>Photo detail</h3>
{% endblock %} {% block content %} {{photo.photo_title}}
<div class="main-content">
    <img src="{{ url_for('static', filename=photo.slug) }}" width="240" height="240" alt="photo" />
</div>
<div class="main-content">
    {{photo.photo_description}}
</div>

<div class="tags">
    {% for tag in tags %}
    <a href="{{ url_for('photos.tag_detail', slug=tag.slug) }}">
        <span class="label label-primary">{{ tag.name }}</span></a> {% endfor %}
</div>
<hr> {% if photo.user_id==current_user.id %}
<a href="{{ url_for('photos.edit_info', slug=photo.id)}}">
        Edit photo info</a> {% endif %} {% endblock %}

app/blueprints/photos/templates/photos/photo_info.html
{% extends 'base.html' %} {% block title %} Photos title {% endblock %} {% block content_title %}
<h3>Photo detail</h3>
{% endblock %} {% block content %} {{photo.photo_title}}
<div class="main-content">
    <img src="{{ url_for('static', filename=photo.slug) }}" width="240" height="240" alt="photo" />
</div>
<div class="main-content">
    {{photo.photo_description}}
</div>

<div class="tags">
    {% for tag in tags %}
    <a href="{{ url_for('photos.tag_detail', slug=tag.slug) }}">
        <span class="label label-primary">{{ tag.name }}</span></a> {% endfor %}
</div>
<hr> {% if photo.user_id==current_user.id %}
<a href="{{ url_for('photos.edit_info', slug=photo.id)}}">
        Edit photo info</a> {% endif %} {% endblock %}

app/blueprints/photos/templates/photos/tag_detail.html
{% extends 'base.html' %} {% block title %} {{ tag.name }} photos {% endblock %} {% block content_title %} Photo for "{{ tag.name }}" tag: {% endblock %} {% block content %} {% for photo in photos %}
<div class="photo">
    <a href="{{ url_for('photos.photo_detail', slug=photo.id) }}">{{ photo.photo_title }}</a>
</div>
{% endfor %}

<div class="main-content">
</div>
{% endblock %}