app/blueprints/events/forms.py
from wtforms import Form, StringField, PasswordField, BooleanField, SubmitField, SelectField, RadioField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, InputRequired
from wtforms import TextAreaField
from wtforms.fields.html5 import DateTimeField

from flask_wtf import FlaskForm

from app import app, tag_choices
from app.models import *


class EventForm(FlaskForm):
    event_title = StringField('Title', validators=[DataRequired()])
    event_body = TextAreaField('Event', validators=[DataRequired()])
    event_time = DateTimeField(
        'Select date of event', format='%Y-%m-%d %H:%M:%S')#, validators=[DataRequired()])
    event_place = TextAreaField('Place, address', validators=[DataRequired()])
    event_geo = TextAreaField('GEO, long, lat', validators=[DataRequired()])
    event_level = StringField('Event level', validators=[DataRequired()])
    tags = RadioField(
        'Select tags', choices=tag_choices)
    # event_crew = db.Column(db.Integer, db.ForeignKey('user.id'))
    submit = SubmitField('Submit')

blueprints/events/forms.py
from wtforms import Form, StringField, PasswordField, BooleanField, SubmitField, SelectField, RadioField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, InputRequired
from wtforms import TextAreaField
from wtforms.fields.html5 import DateTimeField

from flask_wtf import FlaskForm

from app import app
from models import *


class EventForm(FlaskForm):
    event_title = StringField('Title', validators=[DataRequired()])
    event_body = TextAreaField('Event', validators=[DataRequired()])
    event_time = DateTimeField(
        'Which date is your favorite?', format='%Y-%m-%d %H:%M:%S', validators=[DataRequired()])
    event_place = TextAreaField('Place, adress', validators=[DataRequired()])
    event_geo = TextAreaField('GEO, long, lat', validators=[DataRequired()])
    tags = RadioField(
        'Select tags', choices=[(tag.name, tag.slug) for tag in Tag.query.all()], validators=[DataRequired()])
    submit = SubmitField('Submit')

    # id = db.Column(db.Integer, primary_key=True)
    # event_title = db.Column(db.String(140))
    # event_body = db.Column(db.Text)
    # slug = db.Column(db.String(140), unique=True)
    # created = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    
    # event_time = db.Column(db.DateTime)
    # event_place = db.Column(db.Text)
    # event_geo = db.Column(db.Text)

    # event_starter = db.Column(db.Integer, db.ForeignKey('user.id'))
    # event_crew = db.Column(db.Integer, db.ForeignKey('user.id'))

app/blueprints/events/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import flash, redirect
from flask import redirect
from flask import url_for
from flask import request

from flask_login import login_user
from flask_login import logout_user
from flask_login import current_user
from flask_login import login_required

from .forms import EventForm

from app import app
from app import db
from app import log
from app.models import *

try:
    from geopy.geocoders import Nominatim
except:
    redirect('events.index')


events = Blueprint('events', __name__, template_folder='templates')

@events.route('/event_new', methods=['GET', 'POST'])
@login_required
def event_new():
    form = EventForm()
    if request.args == '':
        return redirect('')
    if request.method == 'GET':
        place = request.args
        geolocator = Nominatim(user_agent='habatoo@yandex.ru') 
        location = geolocator.geocode(place.get('search', default = None))
        if location:
            newLocation = str(location.latitude) + str(", ") + str(location.longitude)  
            location_geo = geolocator.reverse([location.latitude, location.longitude]) # 37.62, 55.75
            address = location_geo.address
            event = Event(
            event_title=None, 
            event_body=None, 
            event_time=None,
            event_place = address,
            event_geo = newLocation,
            event_level = None,
            event_author=current_user)
            form = EventForm(
                formdata=request.form, obj=event)
            return render_template('events/new_event.html', form=form)
        else:
            print('no search')
            return redirect('')          

    if form.validate_on_submit():
        event = Event(
            event_title=form.event_title.data, 
            event_body=form.event_body.data, 
            event_time= form.event_time.data,
            event_place = form.event_place.data,
            event_geo = form.event_geo.data,
            event_level = form.event_level.data,
            event_author=current_user)
        event.tags.append(Tag.query.filter_by(name=form.tags.data).first())
        #try:
        db.session.commit()
        flash('Your cane make event!')
        return redirect(url_for('events.index'))
        #except:
        #    redirect('index') # create!!!
    return render_template('events/new_event.html', form=form)

@events.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit_event(slug):
    event = Event.query.filter(Event.slug==slug).first()
    form = EventForm(formdata=request.form, obj=event)

    if form.validate_on_submit():
        event.event_title=form.event_title.data
        event.event_body=form.event_body.data 
        event.event_time= form.event_time.data
        event.event_place = form.event_place.data
        event.event_geo = form.event_geo.data
        event.event_level = form.event_level.data
        try:
            event.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            db.session.commit()
            flash('Your event edited')
            log.info("User '%s' edit event '%s'." % (current_user.username, event.event_title))
            return redirect(url_for('events.event_detail', slug=event.slug))
        except:
           redirect('events.index') 
    form = EventForm(obj=event)
    return render_template('events/edit_event.html', form=form)

@events.route('/', methods=['GET', 'POST'])
@login_required
def index():
    q = request.args.get('q')
    page = request.args.get('page')
    page = request.args.get('page', 1, type=int)
    if q:
        events = Event.query.filter(Event.event_title.contains(q) | Event.event_body.contains(q).all())
    else:
        events = Event.query.order_by(Event.created.desc())
        
    pages = events.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])

    return render_template('events/index.html', pages=pages)


@events.route('/<slug>')
@login_required
def event_detail(slug):
    event = Event.query.filter(Event.slug==slug).first()
    tags = event.tags
    return render_template('events/event_detail.html', event=event, tags=tags)

@events.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    events = tag.events_tags.all()
    return render_template('events/tag_detail.html', tag=tag, events=events)

blueprints/events/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import flash, redirect
from flask import redirect
from flask import url_for
from flask import request

from flask_login import login_user
from flask_login import logout_user
from flask_login import current_user
from flask_login import login_required

from .forms import EventForm

from app import app
from app import db
from models import *

events = Blueprint('events', __name__, template_folder='templates')

@events.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def edit_event(slug):
    event = Event.query.filter(Event.slug==slug).first()
    form = EventForm(formdata=request.form, obj=event)

    if form.validate_on_submit():
        event_title=form.event_title.data, 
        event_body=form.event_body.data, 
        event_time= form.event_time.data,
        event_place = form.event_place.data,
        event_geo = form.event_geo.data,
        try:
            event.tags.append(Tag.query.filter_by(name=form.tags.data).first())
            db.session.commit()
            flash('Your event edited')
            return redirect(url_for('events.post_detail', slug=event.slug))
        except:
           redirect('events.index') 
    form = EventForm(obj=event)
    return render_template('events/edit_event.html', form=form)

@events.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = EventForm()
    if form.validate_on_submit():
        event = Event(
            event_title=form.event_title.data, 
            event_body=form.event_body.data, 
            event_time= form.event_time.data,
            event_place = form.event_place.data,
            event_geo = form.event_geo.data,
            event_author=current_user)
        #try:
        event.tags.append(Tag.query.filter_by(name=form.tags.data).first())
        db.session.commit()
        flash('Your cane make event!')
        return redirect(url_for('events.index'))
        #except:
        #    redirect('index') # create!!!

    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page) 
    else:
        page = 1 
    if q:
        events = Event.query.filter(Event.event_title.contains(q) | Event.event_body.contains(q).all())
    else:
        events = Event.query.order_by(Event.created.desc())
        
    pages = events.paginate(page=page, per_page=app.config['POSTS_PER_PAGE'])

    return render_template('events/index.html', form=form, pages=pages)


@events.route('/<slug>')
@login_required
def event_detail(slug):
    event = Event.query.filter(Event.slug==slug).first()
    tags = event.tags
    return render_template('events/event_detail.html', event=event, tags=tags)

@events.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    events = tag.events_tags.all()
    return render_template('events/tag_detail.html', tag=tag, events=events)

app/blueprints/events/templates/events/edit_event.html
{% extends 'base.html' %} {% block title %} Edit post {% endblock %} {% block content_title %}
<h3>Edit event: {{form.event_title.data}}</h3>
{% endblock %} {% block content %} {% if form %}
<div>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <br>{{ form.event_title.label(class='control-label') }}
            <br> {{ form.event_title(class='form-control') }}
            <br> {% for error in form.event_title.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br> {{ form.event_body.label(class='control-label') }}
            <br> {{ form.event_body(class='form-control') }}
            <br> {% for error in form.event_body.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br>{{ form.tags.label(class='control-label') }}
            <br> {{ form.tags() }}<br> {% for error in form.tags.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br> {{ form.event_time.label(class='control-label') }}
            <br> {{ form.event_time(class='form-control') }}
            <br> {% for error in form.event_time.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br> {{ form.event_place.label(class='control-label') }}
            <br> {{ form.event_place(class='form-control') }}
            <br> {% for error in form.event_place.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br> {{ form.event_geo.label(class='control-label') }}
            <br> {{ form.event_geo(class='form-control') }}
            <br> {% for error in form.event_geo.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br> {{ form.event_level.label(class='control-label') }}
            <br> {{ form.event_level(class='form-control') }}
            <br> {% for error in form.event_level.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

        </div>
        {{ form.submit(class="btn btn-success") }}
    </form>

</div>
{% endif %} {% endblock %}

app/blueprints/events/templates/events/event_detail.html
{% extends 'base.html' %} {% block title %} {{ event.event_title }} {% endblock %} {% block content_title %} {{ event.event_title }} {% endblock %} {% block content %}

<div class="main-content">
    {{ event.event_body }}
</div>
<div class="tags">
    {% for tag in tags %}
    <a href="{{ url_for('events.tag_detail', slug=tag.slug) }}">
        <span class="label label-primary">{{ tag.name }}</span></a> {% endfor %}
</div>
<div>
    event start at: {{ event.event_time }} <br>
    <hr> event adress: {{ event.event_place }} <br>
    <hr> event geo: {{ event.event_geo }} <br>
    <hr> event level: {{ event.event_level }} <br>
    <hr> event author: {{ event.event_starter }} <br> event crew: {{ event.event_crew }}

</div>

<hr> {% if event.event_starter==current_user.id %}
<a href="{{ url_for('events.edit_event', slug=event.slug)}}">
    Edit event</a> {% endif %} {% endblock %}

app/blueprints/events/templates/events/index.html
{% extends 'base.html' %} {% block title %} Blueprint event title {% endblock %} {% block content_title %} All events page {% endblock %} {% block content %}
<br> <a href="{{ url_for('events.event_new') }}">make a New event</a>
<hr> {% for event in pages.items %}
<div class="main-content">
    <table>
        <tr>
            <td><img src="{{ url_for('static', filename=event.event_author.avatar()) }}" width="30" height="30" alt="avatar"></td>
            <td><a href="{{ url_for('user', username=event.event_author.username) }}">
                {{ event.event_author.username }}</a> {{ event.created }} make event :
                <br>
                <a href="{{ url_for('events.event_detail', slug=event.slug) }}">{{ event.event_title }}</a>
                <br> {{ event.event_body }}
                <br> {{ event.event_level }}

                <div class="tags">
                    tags: {% for tag in event.tags %}
                    <a href="{{ url_for('events.tag_detail', slug=tag.slug) }}">
                        <span class="label label-primary">{{ tag.name }}</span></a> {% endfor %}
                </div>
            </td>
        </tr>
    </table>
</div>
<br> {% endfor %}
<nav>
    <ul class="pagination">
        <li {% if not pages.has_prev %} class="disabled" {% endif %}>
            <a href="./?page={{ pages.prev_num }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span></a>
        </li>
        {% for page in pages.iter_pages() %}
        <li {% if page==pages.page %} class="active" {% endif %}><a href="./?page={{ page }}">{{page}} <span class="sr-only">(current)</span></a></li>
        {% endfor %}
        <li {% if not pages.has_next %} class="disabled" {% endif %}>
            <a href="./?page={{ pages.next_num }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span></a>
        </li>
    </ul>
</nav>
{% endblock %}

app/blueprints/events/templates/events/new_event.html
{% extends 'base.html' %} {% block title %} Blueprint event title {% endblock %} {% block content_title %} New event {% endblock %} {% block content %}
<br> New event search place:
<form id="upload-form" action="{{ url_for('events.event_new') }}" method="GET">
    <input type="search" name="search" placeholder="Find here...">
    <input type="submit" value="Send">
</form>


<div>
    {% if form %}
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.event_title.label(class='control-label') }}<br> {{ form.event_title(class='form-control') }}<br> {% for error in form.event_title.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
            <br> {{ form.event_body.label(class='control-label') }}<br> {{ form.event_body(class='form-control') }}<br> {% for error in form.event_body.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br> {{ form.event_time.label(class='control-label') }}<br> {{ form.event_time(class='form-control') }}<br> {% for error in form.event_time.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}

            <br> {{ form.event_place.label(class='control-label') }} {{ form.event_place(class='form-control') }}
            <br> {% for error in form.event_place.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
            <br> {{ form.event_geo.label(class='control-label') }} {{ form.event_geo(class='form-control') }}
            <br>
            <br> {% for error in form.event_geo.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
            <br> {{ form.event_level.label(class='control-label') }}<br> {{ form.event_level(class='form-control') }}<br> {% for error in form.event_level.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
            <br> {{ form.tags.label(class='control-label') }}<br> {{ form.tags() }}<br> {% for error in form.tags.errors %}
            <span style="color: red;">[{{ error }}]</span> {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
    {% endif %}
</div>
{% endblock %}

app/blueprints/events/templates/events/tag_detail.html
{% extends 'base.html' %} {% block title %} {{ tag.name }} events {% endblock %} {% block content_title %} All events for "{{ tag.name }}" tag: {% endblock %} {% block content %} {% for event in events %}
<div class="event">
    <a href="{{ url_for('events.event_detail', slug=event.slug) }}">{{ event.event_title }}</a>
</div>
{% endfor %}

<div class="main-content">
</div>
{% endblock %}